# application.yml
server:
  port: ${SERVER_PORT:10610}
  servlet:
    context-path: ${SERVER_BASE_PATH:/app}
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: Sunrise-Server
  config:
    activate:
      on-profile: docker-full-stack, docker-only-app, local
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration # у меня ваще-то jwt используется

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        ssl.enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet.content-type: text/html

  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: ${SPRING_JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${SPRING_HIBERNATE_FORMAT_SQL:false}
        hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform # ЭТО ДО ТЕХ ПОР, ПОКА 1 БАЗА ДАННЫХ
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    open-in-view: false

logging:
  level:
    com.Sunrise: ${LOGGING_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

app:
  jwt:
    secret: ${JWT_SECRET:mysupersecretkeymysupersecretkeymysupersecretkey}
    expiration: ${APP_JWT_EXPIRATION:36000} # in seconds
    no-jwt-endpoints: /auth/**,/ping,/cache-status
  mail:
    mail-address: ${MAIL_USERNAME}
    base-url: http://${SERVER_IP:localhost}:${SERVER_PORT:10610}${SERVER_BASE_PATH:/app}
  locks:
    # in seconds
    timeout: ${APP_LOCKS_TIMEOUT:5}
    clean-up-expiration: ${APP_LOCKS_CLEAN_UP_EXPIRATION:900}
    clean-up-schedule: ${APP_LOCKS_CLEAN_UP_SCHEDULE:300}
  # нужно добавить в код
  cache:
    max-size:
      user: ${APP_CACHE_MAX_SIZE_USER:100000}
      username-index: ${APP_CACHE_MAX_SIZE_USERNAME_INDEX:150000}
      email-index: ${APP_CACHE_MAX_SIZE_EMAIL_INDEX:150000}
      chat: ${APP_CACHE_MAX_SIZE_CHAT:200000}
      personal-chat-index: ${APP_CACHE_MAX_SIZE_PERSONAL_CHAT_INDEX:100000}
      chat-members: ${APP_CACHE_MAX_SIZE_CHAT_MEMBERS:150000}
      verification-tokens: ${APP_CACHE_MAX_SIZE_VERIFICATION_TOKENS:100000}
      user_chats_pagination: ${APP_CACHE_MAX_SIZE_USER_CHATS_PAGINATION:25000}
      chat_members_pagination: ${APP_CACHE_MAX_SIZE_CHAT_MEMBERS_PAGINATION:50000}
    ttl:
      # in minutes
      user: ${APP_CACHE_TTL_USER:60}
      user-username-index: ${APP_CACHE_TTL_USER_USERNAME_INDEX:60}
      user-email-index: ${APP_CACHE_TTL_USER_EMAIL_INDEX:60}
      chat: ${APP_CACHE_TTL_CHAT:720}
      personal-chat-index: ${APP_CACHE_TTL_PERSONAL_CHAT_INDEX:720}
      chat-members: ${APP_CACHE_TTL_CHAT_MEMBERS:240}
      verification-tokens: ${APP_CACHE_TTL_VERIFICATION_TOKENS:60}
      user_chats_pagination: ${APP_CACHE_TTL_USER_CHATS_PAGINATION:20}
      chat_members_pagination: ${APP_CACHE_TTL_CHAT_MEMBERS_PAGINATION:20}